insert into customer_events (customer_id, time , event_type , staff_id , store_type , tags ) VALUES ( 'chbatey', now(), 'basket_add', 'trevor', 'online', { 'item': 'coffee'}) ;
insert into customer_events (customer_id, time , event_type , staff_id , store_type , tags ) VALUES ( 'chbatey', now(), 'basket_add', 'trevor', 'online', { 'item': 'wine'}) ;
insert into customer_events (customer_id, time , event_type , staff_id , store_type , tags ) VALUES ( 'chbatey', now(), 'basket_add', 'trevor', 'online', { 'item': 'cake'}) ;
